### ISSUE TITLE
Unjust dependency cycle

### ISSUE THREAD

**Issue by TomVanDerSpek** [square/Cleanse#103]
Currently I am facing an issue where Cleanse stops the app due to a detected dependency cycle. 
For example `LoginViewController` has a `Provider<OnboardingViewController>`
The `OnboardingViewController` has a `Provider<LoginViewController>`

This should not be an issue as long as the provider is used outside of the initialiser. I cannot think of a reason to use a Provider's .`get()` directly inside of an initialiser anyway. Is this cycle detection as designed or a bug? 

Example project: https://github.com/TomVanDerSpek/cleanse-tryout-ios/tree/unjust_dependency_cycle_detection

**Comment by sebastianv1** [comment]
As designed. Even though you're injecting in the decorated `Provider<OnboardingViewController>`, cycle detection still resolves using the inner type `OnboardingViewController`. I'm currently working on a fix from your previous issue to use `WeakProvider`.
