### ISSUE TITLE
Example project tests fail to compile

### ISSUE THREAD

**Issue by DJBen** [square/Cleanse#125]
https://github.com/square/Cleanse/blob/99081590f669d0619d1219a035659a68b717e678/Examples/CleanseGithubBrowser/CleanseGithubBrowserTests/CleanseGithubBrowserTests.swift#L20

Error message: `Cannot convert value of type 'MembersPageSettings' to expected argument type 'Factory<AssistedInjectionTags.MembersPageSettingsSeed>'`

It looks the place `MembersPageSettings` meant to have is a partially injected factory, and I am unsure how to fix it.

**Comment by sebastianv1** [comment]
Should be resolved with #127
