### ISSUE TITLE
Add Subcomponents & Scopes

### ISSUE THREAD

**Issue by mikelikespie** [square/Cleanse#2]
Having subcomponents & custom scopes [like dagger](https://google.github.io/dagger/subcomponents.html) will be incredibly useful. This feature needs to be well thought out though.

**Comment by ian-ellis** [comment]
@mikelikespie just wondering what the status on subcomponents is? I'm fairly new to swift/iOS but I've started playing around with Cleanse after using Dagger comprehensively and have come to the point where a subcomponent would be useful (I'm trying to have a root component for application scope but a subcomponent for view controllers / views). Just wondering if it's worth hanging out for it being implemented as development seems to be pretty active or if its better find some other way to achieve what I need.

**Comment by holmes** [comment]
@ian-ellis check out the swift-3 branch. It's got subcomponent support and is what we're currently using within our app.

We definitely need to update the docs for sub-components, I'm not sure what's even there. Best bet is to check out the tests.

**Comment by ian-ellis** [comment]
@holmes thanks, is PropertyInjection still recommended for the app delegate or am I better of creating my own root struct and using that within the AppDelegate didFinishLaunchingWithOptions ?

**Comment by holmes** [comment]
I'd highly recommend a root struct and skip the property injection.

**Comment by holmes** [comment]
Please check the swift3 (soon to be merged to master) for component support.
