### ISSUE TITLE
Installing through CocoaPods returns "Unable to find a specification"

### ISSUE THREAD

**Issue by mariopavlovic** [square/Cleanse#23]
Adding `pod 'Cleanse', '~> 0.1'` returns `[!] Unable to find a specification for 'Cleanse (~> 0.1)'`
Adding `pod 'Cleanse'` returns `[!] Unable to find a specification for 'Cleanse'`

I can see that there's a spec on CocoaPods GitHub, but there's no instruction in readme

Pods version `1.0.1`

**Comment by mikelikespie** [comment]
Haven't added it to readme since I wasn't sure if it was working. Will take a look today

**Comment by dnkoutso** [comment]
@mariopavlovic works for me in a sample app.

Can you check if your master repo includes Cleanse? Its locaed in `~/.cocoapods/repos/master`.

Finally since, CocoaPods 1.0.1 you need to run `pod install --repo-update` to ensure an update of your repos happens.

**Comment by mikelikespie** [comment]
@mariopavlovic please reopen if you're still having issues
