### ISSUE TITLE
Singletons objects will deallocate if becoming unreferenced and reinstantiated

### ISSUE THREAD

**Issue by mikelikespie** [square/Cleanse#25]
This means that singletons aren't always singletons. Its related to retain cycle prevention code that exists. How memory management is done in Cleanse is a bit tricky right now if we want to both avoid retain cycles and allow for weakly referring to singleton dependencies.

**Comment by angadn** [comment]
+1 I am facing this as well, and in my case I was trying to configure a Singleton at one end so as to use it at another. Can confirm that redeclaring it as a `class` instead of a `struct` doesn't fix the issue either. Hence, singletons cannot be reliably in-memory stateful :(

**Comment by mikelikespie** [comment]
@angadn If you check out the branch for https://github.com/square/Cleanse/pull/27 it should have a fix for it.

This branch is pretty deviated from master now, but is the direction we're taking cleanse for the next release

**Comment by sebastianv1** [comment]
Closing because this issue hasn't received any activity lately, feel free to reopen if it's still an issue.
