### ISSUE TITLE
Crash when injecting an optional protocol

### ISSUE THREAD

**Issue by hberenger** [square/Cleanse#26]
Hello,

I faced a crash while playing with Cleanse, when I tried to inject an optional protocol.
The crash can be reproduced in a XCode 7.3 playground with the code below :

```
protocol FooProto {
}

struct Foo : FooProto {
}

struct Bar {
    var foo : FooProto?
    init(foo: FooProto?) {
        self.foo = foo
    }
}

struct BarComponent : Cleanse.Component {
    typealias Root = Bar
    
    func configure<B : Binder>(binder binder: B) {
        binder
            .bind(Bar.self)
            .to(factory: Bar.init)
        binder
            .bind(FooProto.self)
            .to(factory: Foo.init)
    }
}

let bar = try! BarComponent().build()
```

The crash occurs in Provider.swift, in `Provider.makeNew` and `AnyProvider.asCheckedProvider`.
When downcasting from `Any` to `Element` (e.g `getter() as! Element`), you get the following exception :

> Could not cast value of type 'Swift.Optional<FooProto>' to 'FooProto'

The problem is in fact on Swift side : for the moment, it's impossible to cast from `T?` to `Any` and then downcast from `Any` to some protocol implemented by `T` (while it's ok to downcast to `T`...) . I filed an issue for this problem in their backlog : [SR-1999](https://bugs.swift.org/browse/SR-1999)

Also, I came up with some workaround but it uses reflection to unwrap the Optional in Any... Not sure it would conform to the strong-typing spirit of Cleanse, though ^^ 

One could argue that there is no point in injecting optional parameters, but I think it's something which can really occur in real-world circumstances, for exemple when working with an external lib whose constructors take optional parameters.

**Comment by mikelikespie** [comment]
Good find! Yeah this shouldn't be happening... Your use case should be supported. I'll try to take a look at this though, unless you wanna try a fix :)

**Comment by mikelikespie** [comment]
@hberenger 

I was unable to reproduce your crash off the master version.

I created a test with your example verbatim here:

https://github.com/square/Cleanse/pull/28

If you're able to reproduce your bug in a fork or PR, please let me know & reopen this issue.

Can you try xcode 7.3.1 if you're on 7.3?

Thanks,
Mike
