### ISSUE TITLE
Using swift3 version in .podspec / release of 1.0 ?

### ISSUE THREAD

**Issue by duribreux** [square/Cleanse#40]
I'm currently developing a `framework` using the `swift-3` branch of `Cleanse` and I want to release it as a `pod`.

I [saw](https://github.com/square/Cleanse/issues/30#issuecomment-251565728) that you're planning on releasing a major `1.0` of `Cleanse` once you migration to `swift3` is ready like most of the libs I use which is great.

To release my pod I need to add `Cleanse` as dependency in my `.podspec` but it seems I can't specify a `branch` in this file. In consequences when I try to run `pod repo push...` the linter fails because it retrieves the `swift2` version of Cleanse (`0.1.0`) and throws things like:

```
- ERROR | xcodebuild:  Cleanse/Cleanse/BindingBuilder.swift:111:32: error: '.dynamicType' is deprecated. Use 'type(of: ...)' instead
- ERROR | xcodebuild:  Cleanse/Cleanse/BindingBuilder.swift:141:17: error: expected ',' joining parts of a multi-clause condition
- ERROR | xcodebuild:  Cleanse/Cleanse/ComponentVisitor.swift:118:77: error: expected 'let' in conditional
[...]
```

I saw that you have 3 tags on your `master`, `0.1.0`, `1.0.0-a.1` and `1.0.0-a.2` . I tried to specify one of the `1.0.0-a.x` but sadly it's not working:

```
[!] Unable to satisfy the following requirements:
- `Cleanse (~> 1.0.0-a.2)` required by `Podfile`
None of your spec sources contain a spec satisfying the dependency: `Cleanse (~> 1.0.0-a.2)`.
```

And I think the reason is because your `.podspec` still refer to `0.1.0`

Q: Are you planning to release the `1.0.0` as a `pod` soon ? Or am I missing something ?

It seems the only solution for me right now is to fork your `swift-3` and use mine instead but I don't really want to do that.

You can find more information about my problem on this [issue](https://github.com/CocoaPods/CocoaPods/issues/6415) I created on the `cocoapods` project.

**Comment by dnkoutso** [comment]
You can re-publish Cleanse to your internal repo until the official release occurs.

**Comment by holmes** [comment]
Currently pod'd as 1.0-rc1
