### ISSUE TITLE
Subcomponents: Are they the only way to configure components after launch?

### ISSUE THREAD

**Issue by jtwigg** [square/Cleanse#44]
Am I correct in assuming that the tentative Subcomponents would allow me to configure a component after the RootComponent has been configured? 

The use case I'm trying to solve is to configure our UI based on A/B experiment data coming back from the BE, however thats some time after the Root Component has been created. 

Would the solution be to then configure a subcomponent with the resulting A/B test assignments and instantiate the UI from that component?

At present, I cannot find any way to do this in the current Cleanse implementation after a reasonable search.

**Comment by holmes** [comment]
That's one way to do it. 

Or depending on how complex your graph is you can just inject a `Provider<Thing>` and in the binding of the `Thing` test for your feature flag.

**Comment by sebastianv1** [comment]
Closing because this issue hasn't received any activity lately, feel free to reopen if it's still an issue.
