### ISSUE TITLE
InjectProperties from one component to multiple object types

### ISSUE THREAD

**Issue by edenman** [square/Cleanse#45]
Hey yall!  I'm trying to add Cleanse to my app to split out debug-only code from the release build.  I'm trying to minimize my changes at first, so I'm using property injection (yes, I read the "property injection is a second-class citizen section of the readme). 

Here's the component I've defined:

```
struct FooComponent : Cleanse.Component {
	typealias Root = PropertyInjector<AppDelegate>
	
	func configure<B : Binder>(binder binder: B) {
		#if DEBUG
			binder.install(module: DebugModule())
		#else
			binder.install(module: ReleaseModule())
		#endif
		binder.bindPropertyInjectionOf(AppDelegate.self).to(injector: AppDelegate.injectProperties)
		binder.bindPropertyInjectionOf(RequestViewController.self).to(injector: RequestViewController.injectProperties)
	}
}
```
And I'm installing it here in my AppDelegate (this works great):
```
		component = try! FooComponent().build()
		component.injectProperties(into: self)
```
However, if I try to injectProperties on a RequestViewController, the compiler blows up (`Cannot convert value of type 'RequestViewController' to expected argument type 'AppDelegate'`)
```
func inject(obj: RequestViewController) {
	component.injectProperties(into: obj)
}
```

This makes sense because `Component.build()` only returns a `PropertyInjector<AppDelegate>` Can I somehow get access to the underlying graph?  From looking at the source of `Component.build()`, it builds the graph and then just returns the `PropertyInjector<AppDelegate>`, throwing away the graph :sob:

**Comment by holmes** [comment]
Try changing your `Root` to `LegacyObjectGraph`:

```
struct SnapshotTestAppComponent : Cleanse.RootComponent {
    typealias Root = LegacyObjectGraph

    static func configure<B : Binder>(binder: B) {
        binder.include(module: SnapshotTestingModule.self)
    }
}
```

And then in your AppDelegate:

```
        self.objectGraph = try! ComponentFactory.of(SnapshotTestAppComponent.self).build()
        self.objectGraph.injectPropertiesIntoObject(object: self)
```

**Comment by edenman** [comment]
talked to @holmes offline...LegacyObjectGraph isn't available in the version of Cleanse that is published in cocoapods.  Here's what we arrived at, instead:

the component:
```
struct FooComponent : Cleanse.Component {
	struct Injector {
		let app: PropertyInjector<AppDelegate>
		let vc: PropertyInjector<RequestViewController>
	}
	
	typealias Root = Injector
	
	func configure<B : Binder>(binder binder: B) {
		#if DEBUG
			binder.install(module: DebugModule())
		#else
			binder.install(module: ReleaseModule())
		#endif
		binder.bind(Injector.self).to(factory: Injector.init)
		binder.bindPropertyInjectionOf(AppDelegate.self).to(injector: AppDelegate.injectProperties)
		binder.bindPropertyInjectionOf(RequestViewController.self).to(injector: RequestViewController.injectProperties)
	}
}
```
then in AppDelegate,
```
func inject(obj: RequestViewController) {
	component.vc.injectProperties(into: obj)
}
```
This works, but it's _really_ clunky...every time I add a new injectable type, I have to add a new `bindPropertyInjectionOf` line, a new field on `Injector`, _and_ a new wrapper method in `AppDelegate` so the thing being injected doesn't have to know about any of this.

Look forward to LegacyObjectGraph being exposed!  Or since it sounds like that's a temporary shim, a more stable API that can inject multiple types would be even better :)

**Comment by sebastianv1** [comment]
Closing because this issue hasn't received any activity lately, feel free to reopen if it's still an issue.
