### ISSUE TITLE
How are Singleton Binders declared?

### ISSUE THREAD

**Issue by pusolito** [square/Cleanse#50]
I'm trying to use Binder<Singleton> in my project and it does not work.  I only see UnscopedBinder.  Can you explain what unscoped means and how to define things in singleton scope?

**Comment by holmes** [comment]
Sorry, we really need to update documentation and examples for this. As well as merge the Swift 3 branch into master. Which hopefully you're using.

Here's how we use Singleton(s):

```

import Foundation
import Cleanse

public struct Singleton : Cleanse.Scope {
}

public typealias SingletonBinder = Binder<Singleton>

extension BindingBuilder where Binder : BinderType, MaybeScope == Unscoped, Binder.Scope == Singleton {
    /// Backwards compatability shim
    public func asSingleton() -> Cleanse.ScopedBindingDecorator<Self, Self.Binder.Scope> {
        return self.sharedInScope()
    }
}
```

And then you can just bind using `asSingleton()` to make things super easy.

```
public static func configure(binder: SingletonBinder) {
        binder
            .bind(Foo.self)
            .asSingleton()
            .to { Foo() }
}
```

**Comment by pusolito** [comment]
Thanks for clarifying.  This is exactly what I started doing after digging around in your code and seeing that pattern.  +1 for the merge and enriched docs.

I just want to say how well designed I think Cleanse is.  Please keep at it.

**Comment by bboy79** [comment]
Hi! First of all, sorry if this isn't the right place, but I didn't see the need to create a new issue. Is there any ETA on when will the examples and documentation be updated? I'm using the Swift 3 branch, but I'm facing some difficulties that would easily be avoided with docs and/or examples. Thank you in advance, and thank you for developing the library!

**Comment by holmes** [comment]
@bboy79 Examples have been updated. Docs coming up soon!
