### ISSUE TITLE
How should I solve cyclical dependencies in Cleanse?

### ISSUE THREAD

**Issue by mpp-davel** [square/Cleanse#52]
Hi, 

I'm using the `swift-3` branch of Cleanse and have a question related to solving cyclical dependencies:

I have a case where `ModuleA` depends on `ModuleB`, and `ModuleB` depends on `ModuleA`.

In order to work around this cyclic dependency I thought making `ModuleA` depend on `Provider<ModuleB>` should work, but it does not and I still get the following error: `*** ModuleA *** Dependency Cycle Detected`

What is the right approach using Cleanse to work around this issue?

Any help would be most appreciated! Cheers :)

**Comment by holmes** [comment]
I think you can use a `WeakProvider`. 

But in all honesty you should really remove the circular dependency.
