### ISSUE TITLE
Cleanse is broken in Swift 3.2

### ISSUE THREAD

**Issue by holmes** [square/Cleanse#59]
A few silly little warnings. 

But the big issue is when declaring a `Component` that has a `Seed` of `Void`. 

Now when calling `componentFactory.build()` we're getting 

```
/work/Cleanse2/CleanseTests/ComponentVisitorTests.swift:29:41: Missing argument for parameter #1 in call
```

I've tried passing `Void` but then it says 
```
/work/Cleanse2/CleanseTests/ComponentVisitorTests.swift:29:40: Argument passed to call that takes no arguments
```

We'll have to find the magic incantation.

**Comment by holmes** [comment]
Created a swift-3.2 branch for the changes.

**Comment by Daemon-Devarshi** [comment]
Any update on this issue?

**Comment by holmes** [comment]
No sorry, haven't had any time to look into it.

**Comment by sebastianv1** [comment]
@holmes Resolve this one too. Should be fixed.
