### ISSUE TITLE
Remove "LegacyObjectGraph" (if desired)

### ISSUE THREAD

**Issue by mikelikespie** [square/Cleanse#6]
The legacy object graph exists to support use of requesting objects in an objective-c environment. The primary purpose of this is to facilitate migration from an older, internal DI library, but may be generally useful.

Getting rid of this appendage will simplify the code a little bit.

**Comment by sebastianv1** [comment]
Closing because this issue hasn't received any activity lately, feel free to reopen if it's still an issue.
