### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by lotz** [square/Cleanse#61]
Not a lot of action in here in some time. Just wondering if I should look elsewhere for a Swift DI framework (answer: probably). Thanks!

**Comment by holmes** [comment]
@lotz It's very much alive in our Appointments app on iOS. We just haven't seen much activity from the community.

We are lacking Swift 4 support, which we should probably get on.

**Comment by startupthekid** [comment]
I would love to use it; I've been looking forward to it for some time. I tried it out in the early stages and I really liked the API and how it was setup. What can I do to help get it out to everyone?

**Comment by holmes** [comment]
@startupthekid we could use help migrating to swift 4. That and blog posts are probably the most helpful.

**Comment by startupthekid** [comment]
Gotcha, what's the latest branch I should fork?

**Comment by holmes** [comment]
Looks like `swift-3.2` is the latest. Man we're behind.

**Comment by startupthekid** [comment]
#62

**Comment by sebastianv1** [comment]
@startupthekid We've updated the code to support swift4. Should compile without any issues.
@holmes Does this issue seem okay to resolve?

**Comment by startupthekid** [comment]
Sweet! Would you guys mind turning on the TravisCI for this repo as well? My first PR will be getting that working and then linting (SwiftLint) and automation (Fastlane).

Are the tests fixed as well? I've been trying to figure out how to fix them these past few days but I've been stuck learning how Cleanse works internally and haven't made much progress. Apart from the lining, getting travis working, and automation working, I'm not sure where else I can contribute but glad to help out however.

**Comment by holmes** [comment]
@sebastianv1 can you try turning on TravisCI?

**Comment by sebastianv1** [comment]
@holmes Can do.
@startupthekid The tests should all be working (although still running on Swift3). And we're always open to contributions! I think adding a linter to Cleanse is a good idea, but I'm not quite sure what Fastlane would achieve.

**Comment by startupthekid** [comment]
Not so much Fastlane I guess, more just some automation tool for doing things like running tests, building frameworks for each platform, releasing new versions and pushing to cocoapods, etc. Fastlane is just the most popular of iOS automation tools but bash/ruby/python scripts work well too.

**Comment by sebastianv1** [comment]
I see. Well we already have TravisCI running our tests against any PR to master, but feel free to open a PR for any improvements where you see fit.
