### ISSUE TITLE
Swift 4 DI framework alternatives?

### ISSUE THREAD

**Issue by ferologics** [square/Cleanse#68]
Was cheering for the swift 4 support. bummer.
I hope #67 can be resolved soon 💪 🔢

Personal runner ups:
0️⃣ `factor` 1️⃣ `factory` 2️⃣ `factoruple` 3️⃣ `factoryplet` 4️⃣ `factoruple` 5️⃣ `factopenta` | `pentafactory` 6️⃣ `hexafactory` | `factorhex`

In the mean time, can anybody point me to a simple swift 4 compatible DI framework?

**Comment by sebastianv1** [comment]
@ferologics We have a working swift4 solution (#69) that we can hopefully land soon!
