### ISSUE TITLE
What would it take to get an updated version into Cocoapods?

### ISSUE THREAD

**Issue by CodyDunlap** [square/Cleanse#74]
I'd like to use this library in my app but I use Cocoapods for Dependency Management. The latest version in Cocoapods is 0.1.0, though it appears you guys are much further than that.

**Comment by sebastianv1** [comment]
We'll push a new version to CocoaPods today. Thanks for the patience!

**Comment by CodyDunlap** [comment]
Thanks!

**Comment by sebastianv1** [comment]
Updated in the master CocoaPods spec repo.
