### ISSUE TITLE
Question: Is there a better way to use constructor injection for ViewControllers?

### ISSUE THREAD

**Issue by CodyDunlap** [square/Cleanse#77]
So I have gone through all of example code that I can find on Cleanse, as well as the documentation. As my app can have rather deep navigation at times, I'm struggling with finding a clean solution to injecting dependencies into my view controllers. The problem I'm running into is that with the following scenario:

ViewControllerA - depends on Service1 - presents ViewControllerB
ViewControllerB - depends on Service1 and Service2 - presents ViewControllerC
ViewControllerC - depends on Service3 and Service4

I'm using constructor injection (not using storyboard), but because of the navigation, even though ViewControllerA and ViewControllerB have no dependency on Service3 and Service4, they end up having a dependency on them just so they can pass those dependencies down the navigation chain to ViewControllerC. 

I've toyed with the idea of just using property injection for each of my ViewControllers like I do for AppDelegate and also like I would do if I were using Storyboard, but I really don't want to do that. Am I missing something? Is there a better way to manage this? Or this just something I have to deal with? Coming from Android with Dagger/Dagger2, this just feels wrong.

**Comment by sebastianv1** [comment]
If I'm understanding your situation correctly, shouldn't you be able to bind `ViewControllerC` using `Service3` and `Service4` using Cleanse and then simply inject that object into `ViewControllerB`, thus removing the need to inject `Service3` and `Service4`. 

If you're injecting `Service3` and `Service4` into `ViewControllerB`, then it sounds like you might be constructing `ViewControllerC` manually (not through Cleanse).

For example:

```
bind(Service3.self).to { Service3() }
bind(Service4.self).to { Service4() }

bind(ViewControllerC.self) to { service3: Service3, service4: Service4 -> ViewControllerC in
    return ViewControllerC(services: [service3, service4])
}
bind(ViewControllerB.self) to {  vc: ViewControllerC -> ViewControllerB in
    return ViewControllerB(vc: vc)
}
```

**Comment by CodyDunlap** [comment]
Sorry, yes. I think I was a little unclear. That's what I'm doing now. So ViewControllerB looks like:

init(service1: Service1, service2: Service2, nextViewController: ViewControllerC) {
   ...
}

But where I feel like I'm doing something wrong/missing something, is in the way those ViewControllers are being injected, because my example is actually quite simplified from my real use case. In some ViewControllers, there may be 5+ potential ViewControllers to be navigated to depending on what the user selects. My fear is that an instance of all of these "potential" view controllers is being instantiated even if they are never used, which in turn will cause all of their "potential" dependencies to be instantiated as well.

**Comment by sebastianv1** [comment]
Ah I see.

What you could do is turn them all into `Providers` which would only instantiate them when you call `.get()`.

So your init would look like:
```
init(service1: Service1, service2: Service2, nextViewController: Provider<ViewControllerC>) { ... }
```
And when you want to actually instantiate an instance of `ViewControllerC` (or any other view controller depending on the user input), you would do something like this:
```
func presentC() {
    self.navigationController.push(vc: nextViewController.get())
}
```

**Comment by sebastianv1** [comment]
Closing. Feel free to reopen if that didn't answer your question.

**Comment by CodyDunlap** [comment]
I think that will get me what I need, I just haven't had a chance to try it yet. Thanks!
