### ISSUE TITLE
Swift 4.2 incompatibility with the latest Cocoapods version

### ISSUE THREAD

**Issue by naandonov** [square/Cleanse#83]
The newest avaliable Cleanse version in the Cocoapods repo is 4.1.1, which does not contain the swift 4.2 incompitabilities refactoring, which was introduced in 4.1.2. Will there be a version update soon? Thank you.

**Comment by sebastianv1** [comment]
Apologies for the delay. Will push a new version to trunk later today or tomorrow. (There are some issues with pod spec lint I need to resolve)

**Comment by sebastianv1** [comment]
Published podspec v4.2 to the CocoaPods specs repo. Thanks for your patience.
