### ISSUE TITLE
Clean up Code Generation

### ISSUE THREAD

**Issue by mikelikespie** [square/Cleanse#9]
The code generation for the multiple Arities binding is very gnarly. It should be DRYed a lot.

We've had success in other projects using code generation that has a DSL like the following

``` swift
    print("public static let descriptor: FileDescriptor =", trailing: "()") {
        for d in f.dependencies {
            print("\(d.swiftOuterStructName).initializeFile()")
        }
        print("return try! DescriptorPool.generatedPool.buildFile(descriptorProto)")
    }
```

**Comment by sebastianv1** [comment]
Closing because this issue hasn't received any activity lately, feel free to reopen if it's still an issue.
