### ISSUE TITLE
AppDelegate.injectProperties method declaration is not shown in the README

### ISSUE THREAD

**Issue by HenriLangenhoven** [square/Cleanse#94]
The title pretty much sums it up.

I suspect the method declaration was meant to go after this section:

> **Note**: Even though we can configure property injection with closures, it is generally cleaner to make a method that sets the
> properties like we did with `AppDelegate.injectProperties`:

**Comment by sebastianv1** [comment]
Ah thanks for calling that out. We did need a space after `code-block::` and a newline. Putting up a PR now.
